name: Build, Test & Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Install dependencies
        run: go mod download

      - name: Run Tests...
        run: go test ./...

      - name: Build binary
        run: go build -o pokedexcli main.go
  
  release:
    name: Release CLI
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod download

      - name: Build release binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/pokedexcli-linux main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/pokedexcli-macos main.go
          GOOS=windows GOARCH=amd64 go build -o dist/pokedexcli-windows.exe main.go
      
      - name: Upload binaries to Github Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
