name: Build, Test & Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false
      
      - name: Install dependencies
        run: go mod download

      - name: Run Tests...
        run: go test ./...

      - name: Build binary
        run: go build -o pokedexcli main.go
  
  create-tag:
     name: Create Tag
     needs: build
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Bump version and push tag
         uses: anothrNick/github-tag-action@1.67.0
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           WITH_V: true
           DEFAULT_BUMP: patch
           INITIAL_VERSION: 0.0.0
  
  release:
    name: Release CLI
    needs: create-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: Install dependencies
        run: go mod download

      - name: Build release binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/pokedexcli-linux main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/pokedexcli-macos main.go
          GOOS=windows GOARCH=amd64 go build -o dist/pokedexcli-windows.exe main.go
      
      - name: Upload binaries to Github Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
